export const themes = [
  {
    id: "01",
    name: "dreamy lake view",
    mainColor: "#282623",
    secondaryColor: "#F7BDAC",
    headerFontColor: "#282623",
    mainFontColor: "#ffffffc1",
    modulColor: "#ffffff0d",
    picture: "dreamy-lake-small",
  },

  {
    id: "02",
    name: "beautiful mountains",
    mainColor: "#260C0D",
    secondaryColor: "#FDD7A8",
    headerFontColor: "#260C0D",
    mainFontColor: "#ffffffc1",
    modulColor: "#ffffff0d",
    picture: "beautiful-mountains-small",
  },
  {
    id: "03",
    name: "awakening city",
    mainColor: "#12031E",
    secondaryColor: "#918EED",
    headerFontColor: "#ffffffc1",
    mainFontColor: "#ffffffc1",
    modulColor: "#ffffff0d",
    picture: "awakening-city",
  },
  {
    id: "04",
    name: "sunset",
    mainColor: "#1E203D",
    secondaryColor: "#F36281",
    headerFontColor: "#ffffffc1",
    mainFontColor: "#ffffffc1",
    modulColor: "#ffffff0d",
    picture: "sunset",
  },
  {
    id: "05",
    name: "beach",
    mainColor: "#F3D8B5",
    secondaryColor: "#BAE5F6",
    headerFontColor: "#907311",
    mainFontColor: "#907311",
    modulColor: "#90721152",
    picture: "beach",
  },
  {
    id: "06",
    name: "sidney",
    mainColor: "#060600",
    secondaryColor: "#D36A00",
    headerFontColor: "#ffffffc1",
    mainFontColor: "#ffffffc1",
    modulColor: "#ffffff0d",
    picture: "sidney",
  },
  {
    id: "07",
    name: "lila",
    mainColor: "#1F2035",
    secondaryColor: "#D0BADE",
    headerFontColor: "#5C517B",
    mainFontColor: "#ffffffc1",
    modulColor: "#ffffff0d",
    picture: "lila",
  },
  {
    id: "08",
    name: "spooky",
    mainColor: "#000",
    secondaryColor: "#D0BADE",
    headerFontColor: "#ffffffc1",
    mainFontColor: "#ffffffc1",
    modulColor: "#a6596148",
    picture: "spooky",
  },
  {
    id: "09",
    name: "blue-night",
    mainColor: "#00172D",
    secondaryColor: "#C0C0E1",
    headerFontColor: "#ffffffc1",
    mainFontColor: "#ffffffc1",
    modulColor: "#ffffff0d",
    picture: "blue-night",
  },
  {
    id: "10",
    name: "green-night",
    mainColor: "#132F43",
    secondaryColor: "#45A6B1",
    headerFontColor: "#ffffffc1",
    mainFontColor: "#ffffffc1",
    modulColor: "#ffffff0d",
    picture: "green-night",
  },
];
